[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
[rpc_endpoints]
canto_mainnet = "https://canto.slingshot.finance"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config